Algoritmo "Números de 1 a 10 (com enquanto ... faca)"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Lista de 1 a 10
// Autor(a)    : Rodrigo Aglinskas
// Data atual  : 23/07/2021
Var j: inteiro
// Seção de Declarações das variáveis
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
j <- 1
enquanto j <= 10 faca
escreval(j)
j <- j + 1
fimenquanto
Fimalgoritmo